# Generated by Django 4.2.30 on 2026-04-25 02:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('nome_fantasia', models.CharField(blank=True, max_length=200)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('endereco', models.TextField(blank=True)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(blank=True, max_length=2)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('total_uhs', models.IntegerField(default=0, help_text='Total de unidades habitacionais')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='empresas/logos/')),
                ('cor_primaria', models.CharField(default='#2dd4a0', max_length=7)),
                ('fuso_horario', models.CharField(default='America/Sao_Paulo', max_length=50)),
                ('moeda', models.CharField(default='BRL', max_length=3)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='MembroEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(choices=[('admin', 'Administrador'), ('gerente', 'Gerente'), ('operacional', 'Operacional'), ('visualizador', 'Visualizador')], default='operacional', max_length=20)),
                ('modulos_permitidos', models.JSONField(blank=True, default=list, help_text='Lista de módulos acessíveis, ex: ["custos","compras"]. Vazio = todos.')),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros', to='empresas.empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresas_membro', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membro',
                'verbose_name_plural': 'Membros',
                'ordering': ['empresa', 'usuario'],
                'unique_together': {('usuario', 'empresa')},
            },
        ),
    ]
