# Generated by Django 4.2.30 on 2026-04-25 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArquivoImportado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('total_registros', models.IntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Arquivo Importado',
                'verbose_name_plural': 'Arquivos Importados',
                'ordering': ['-data_upload'],
            },
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=500)),
                ('grupo', models.CharField(default='Sem categoria', max_length=255)),
                ('cc', models.CharField(default='Sem CC', max_length=255, verbose_name='Centro de Custo')),
                ('mes', models.CharField(max_length=7)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('qtde', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('preco_unit', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('arquivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='custos.arquivoimportado')),
            ],
            options={
                'verbose_name': 'Movimentação',
                'verbose_name_plural': 'Movimentações',
                'indexes': [models.Index(fields=['arquivo', 'mes'], name='custos_movi_arquivo_4b61a7_idx'), models.Index(fields=['cc'], name='custos_movi_cc_af7aee_idx'), models.Index(fields=['grupo'], name='custos_movi_grupo_845c4f_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='arquivoimportado',
            index=models.Index(fields=['empresa', 'ativo'], name='custos_arqu_empresa_429f2b_idx'),
        ),
    ]
