# Generated by Django 4.2.30 on 2026-04-26 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0002_must_change_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransacaoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_autorizacao', models.CharField(max_length=100)),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=12)),
                ('num_parcela', models.IntegerField(default=0)),
                ('num_doc', models.CharField(blank=True, max_length=100)),
                ('seq_nf', models.CharField(blank=True, max_length=100)),
                ('obs', models.CharField(blank=True, max_length=500)),
                ('hospede', models.CharField(blank=True, max_length=200)),
                ('inst_pagto', models.CharField(blank=True, max_length=100)),
                ('codinome', models.CharField(blank=True, max_length=100)),
                ('data', models.DateField(blank=True, null=True)),
                ('arquivo_nome', models.CharField(blank=True, max_length=200)),
                ('importado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes_sistema', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Transação Sistema',
                'verbose_name_plural': 'Transações Sistema',
                'ordering': ['data', 'cod_autorizacao'],
            },
        ),
        migrations.CreateModel(
            name='PeriodoConciliado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ate', models.DateField()),
                ('total_transacoes', models.IntegerField(default=0)),
                ('total_ok', models.IntegerField(default=0)),
                ('observacao', models.TextField(blank=True)),
                ('fechado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodos_conciliados', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Período Conciliado',
                'verbose_name_plural': 'Períodos Conciliados',
                'ordering': ['data_ate'],
            },
        ),
        migrations.CreateModel(
            name='LogConciliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icone', models.CharField(blank=True, max_length=10)),
                ('descricao', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_conciliacao', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Log Conciliação',
                'verbose_name_plural': 'Logs Conciliação',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='TransacaoOperadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operadora', models.CharField(max_length=50)),
                ('data', models.DateField()),
                ('hora', models.CharField(blank=True, max_length=10)),
                ('autorizacao', models.CharField(max_length=100)),
                ('nsu', models.CharField(blank=True, max_length=100)),
                ('bandeira', models.CharField(blank=True, max_length=50)),
                ('modalidade', models.CharField(blank=True, max_length=100)),
                ('num_cartao', models.CharField(blank=True, max_length=50)),
                ('valor_operadora', models.DecimalField(decimal_places=2, max_digits=12)),
                ('taxa', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_liquido', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('parcelas', models.IntegerField(default=0)),
                ('status_venda', models.CharField(blank=True, max_length=50)),
                ('valor_sistema', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('diferenca', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('qtd_operadora', models.IntegerField(default=1)),
                ('qtd_sistema', models.IntegerField(default=0)),
                ('agrupamento', models.CharField(blank=True, max_length=100)),
                ('tipo_match', models.CharField(blank=True, max_length=50)),
                ('tipo_grupo', models.CharField(blank=True, max_length=50)),
                ('soma_positivos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('soma_negativos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('num_controle', models.CharField(blank=True, max_length=100)),
                ('num_doc_sis', models.CharField(blank=True, max_length=100)),
                ('bandeira_sistema', models.CharField(blank=True, max_length=100)),
                ('hospede', models.CharField(blank=True, max_length=200)),
                ('usuario_sistema', models.CharField(blank=True, max_length=100)),
                ('info_sistema', models.CharField(blank=True, max_length=500)),
                ('valida_auth', models.BooleanField(default=True)),
                ('valida_nsu', models.BooleanField(default=True)),
                ('valida_bandeira', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('conciliado', 'Conciliado'), ('divergente', 'Divergente'), ('arredondavel', 'Arredondável'), ('ajustado', 'Ajustado'), ('arredondado', 'Arredondado'), ('somente_op', 'Só Operadora'), ('agrupado', 'Agrupado'), ('pix_ignorado', 'PIX Ignorado')], default='pendente', max_length=20)),
                ('locked', models.BooleanField(default=False)),
                ('ajuste', models.JSONField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes_cartao', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Transação Operadora',
                'verbose_name_plural': 'Transações Operadoras',
                'ordering': ['data', 'operadora', 'autorizacao'],
                'unique_together': {('empresa', 'operadora', 'autorizacao', 'data', 'nsu', 'valor_operadora')},
            },
        ),
    ]
