# Generated by Django 4.2.30 on 2026-05-25 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0002_must_change_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArquivoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('total_registros', models.IntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Arquivo de Estoque',
                'verbose_name_plural': 'Arquivos de Estoque',
                'ordering': ['-data_upload'],
            },
        ),
        migrations.CreateModel(
            name='EntradaNota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('item', models.CharField(blank=True, default='', max_length=500)),
                ('classe', models.CharField(blank=True, default='', max_length=200)),
                ('almox', models.CharField(blank=True, default='', max_length=200)),
                ('fornecedor', models.CharField(blank=True, default='', max_length=300)),
                ('nf', models.CharField(blank=True, default='', max_length=100)),
                ('qtde', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('preco', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('unidade', models.CharField(blank=True, default='', max_length=50)),
                ('controlado', models.CharField(blank=True, default='', max_length=1)),
                ('arquivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='estoque.arquivoestoque')),
            ],
            options={
                'indexes': [models.Index(fields=['arquivo', 'data'], name='estoque_ent_arquivo_20116f_idx'), models.Index(fields=['arquivo', 'classe'], name='estoque_ent_arquivo_f09756_idx'), models.Index(fields=['arquivo', 'almox'], name='estoque_ent_arquivo_b05c5e_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='arquivoestoque',
            index=models.Index(fields=['empresa', 'ativo'], name='estoque_arq_empresa_094da3_idx'),
        ),
    ]
