# Generated by Django 4.2.30 on 2026-04-24 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArquivoImportado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('total_registros', models.IntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Arquivo Importado',
                'verbose_name_plural': 'Arquivos Importados',
                'ordering': ['-data_upload'],
            },
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=500)),
                ('grupo', models.CharField(default='Sem categoria', max_length=255)),
                ('cc', models.CharField(default='Sem CC', max_length=255, verbose_name='Centro de Custo')),
                ('mes', models.CharField(max_length=7)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('qtde', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('preco_unit', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('arquivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='dashboard.arquivoimportado')),
            ],
            options={
                'verbose_name': 'Movimentação',
                'verbose_name_plural': 'Movimentações',
                'indexes': [models.Index(fields=['arquivo', 'mes'], name='dashboard_m_arquivo_e359ba_idx'), models.Index(fields=['cc'], name='dashboard_m_cc_78c99f_idx'), models.Index(fields=['grupo'], name='dashboard_m_grupo_97131e_idx')],
            },
        ),
    ]
