# Generated by Django 4.2.30 on 2026-06-19 01:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0002_must_change_password'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaAlimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('custo_kg_medio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ativo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Categoria de Alimento',
                'verbose_name_plural': 'Categorias de Alimento',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('ativo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Unidade',
                'verbose_name_plural': 'Unidades',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ativo', models.BooleanField(default=True)),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setores', to='desperdicio.unidade')),
            ],
            options={
                'verbose_name': 'Setor',
                'verbose_name_plural': 'Setores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='RegistroDesperdicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_perda', models.CharField(choices=[('sobra_buffet', 'Sobra de Buffet'), ('producao', 'Erro de Produção'), ('vencido', 'Vencido/Validade'), ('outro', 'Outro')], default='sobra_buffet', max_length=20)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='desperdicio/%Y/%m/')),
                ('alimento_ia', models.CharField(blank=True, default='', max_length=200)),
                ('confianca_ia', models.FloatField(blank=True, null=True)),
                ('peso_kg', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ('custo_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_perda', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('turno', models.CharField(choices=[('manha', 'Manhã'), ('tarde', 'Tarde'), ('noite', 'Noite')], default='manha', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros', to='desperdicio.categoriaalimento')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_desperdicio', to=settings.AUTH_USER_MODEL)),
                ('setor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros', to='desperdicio.setor')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='desperdicio.unidade')),
            ],
            options={
                'verbose_name': 'Registro de Desperdício',
                'verbose_name_plural': 'Registros de Desperdício',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContagemClientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('n_clientes', models.IntegerField(default=0)),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contagens', to='desperdicio.unidade')),
            ],
            options={
                'verbose_name': 'Contagem de Clientes',
                'verbose_name_plural': 'Contagens de Clientes',
                'ordering': ['-data'],
            },
        ),
        migrations.AddIndex(
            model_name='unidade',
            index=models.Index(fields=['empresa', 'ativo'], name='desperdicio_empresa_0772b9_idx'),
        ),
        migrations.AddIndex(
            model_name='registrodesperdicio',
            index=models.Index(fields=['unidade', 'created_at'], name='desperdicio_unidade_cb1bd1_idx'),
        ),
        migrations.AddIndex(
            model_name='registrodesperdicio',
            index=models.Index(fields=['unidade', 'setor'], name='desperdicio_unidade_087964_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contagemclientes',
            unique_together={('unidade', 'data')},
        ),
        migrations.AddIndex(
            model_name='categoriaalimento',
            index=models.Index(fields=['empresa', 'ativo'], name='desperdicio_empresa_c928f8_idx'),
        ),
    ]
