# Generated by Django 4.2.30 on 2026-06-19 21:20

import apps.desperdicio.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_must_change_password'),
        ('desperdicio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, default=apps.desperdicio.models.gen_token, max_length=64, unique=True)),
                ('nome', models.CharField(default='Tablet Cozinha', max_length=100)),
                ('ativo', models.BooleanField(default=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='empresas.empresa')),
                ('setor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispositivos', to='desperdicio.setor')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos', to='desperdicio.unidade')),
            ],
            options={
                'verbose_name': 'Dispositivo',
                'verbose_name_plural': 'Dispositivos',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='categoriaalimento',
            name='estoque_classe',
            field=models.CharField(blank=True, default='', help_text='Classe do item no módulo Estoque (Entrada de Notas) usada para buscar o custo. Ex: "Carnes Bovinas".', max_length=200),
        ),
        migrations.AddField(
            model_name='categoriaalimento',
            name='modo_custo',
            field=models.CharField(choices=[('manual', 'Valor digitado manualmente'), ('estoque_medio', 'Custo médio do Estoque (Entrada de Notas)'), ('estoque_ultimo', 'Último preço pago no Estoque (Entrada de Notas)')], default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='categoriaalimento',
            name='custo_kg_medio',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Usado quando modo_custo=manual, ou como fallback se não houver dado no Estoque.', max_digits=10),
        ),
        migrations.CreateModel(
            name='DispositivoPairingCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, default=apps.desperdicio.models.gen_pair_code, max_length=10, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('usado', models.BooleanField(default=False)),
                ('dispositivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pairing_codes', to='desperdicio.dispositivo')),
            ],
            options={
                'verbose_name': 'Código de Pareamento',
            },
        ),
    ]
