# Generated by Django 4.2.30 on 2026-06-20 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_must_change_password'),
        ('desperdicio', '0002_dispositivo_categoriaalimento_estoque_classe_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPerda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ativo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Tipo de Perda',
                'verbose_name_plural': 'Tipos de Perda',
                'ordering': ['nome'],
            },
        ),
        migrations.RemoveField(
            model_name='registrodesperdicio',
            name='tipo_perda',
        ),
        migrations.AddField(
            model_name='registrodesperdicio',
            name='tipo_perda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros', to='desperdicio.tipoperda'),
        ),
        migrations.AddIndex(
            model_name='tipoperda',
            index=models.Index(fields=['empresa', 'ativo'], name='desperdicio_empresa_874e66_idx'),
        ),
    ]
