# Generated by Django 4.2.30 on 2026-06-20 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_must_change_password'),
        ('desperdicio', '0004_seed_tipos_perda_padrao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contagemclientes',
            options={'ordering': ['-data'], 'verbose_name': 'Contagem de Refeições Servidas', 'verbose_name_plural': 'Contagens de Refeições Servidas'},
        ),
        migrations.RemoveField(
            model_name='registrodesperdicio',
            name='turno',
        ),
        migrations.AlterField(
            model_name='contagemclientes',
            name='n_clientes',
            field=models.IntegerField(default=0, help_text='Quantidade de refeições/hóspedes servidos nesse período.'),
        ),
        migrations.CreateModel(
            name='Refeicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ativo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Refeição',
                'verbose_name_plural': 'Refeições',
                'ordering': ['nome'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='contagemclientes',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='contagemclientes',
            name='refeicao',
            field=models.ForeignKey(blank=True, help_text='Vazio = contagem total do dia, não vinculada a uma refeição específica.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contagens', to='desperdicio.refeicao'),
        ),
        migrations.AddField(
            model_name='registrodesperdicio',
            name='refeicao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros', to='desperdicio.refeicao'),
        ),
        migrations.AlterUniqueTogether(
            name='contagemclientes',
            unique_together={('unidade', 'data', 'refeicao')},
        ),
        migrations.AddIndex(
            model_name='refeicao',
            index=models.Index(fields=['empresa', 'ativo'], name='desperdicio_empresa_f99760_idx'),
        ),
    ]
