# Generated by Django 4.2.30 on 2026-06-22 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desperdicio', '0006_seed_refeicoes_padrao'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaalimento',
            name='estoque_palavra_chave',
            field=models.CharField(blank=True, default='', help_text='Filtra pelo nome do item (ex: "arroz") em vez da classe inteira — evita média com itens muito diferentes de preço dentro da mesma classe.', max_length=200),
        ),
    ]
