# Generated by Django 4.2.30 on 2026-09-26 00:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('empresas', '0002_must_change_password'),
        ('enxoval', '0002_coletorenxoval'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessaoLeitura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_mov', models.CharField(max_length=10)),
                ('responsavel', models.CharField(blank=True, max_length=120)),
                ('epcs', models.JSONField(default=list)),
                ('aberta', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='empresas.empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes_enxoval', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sessão de Leitura',
                'verbose_name_plural': 'Sessões de Leitura',
                'ordering': ['-atualizado_em'],
                'indexes': [models.Index(fields=['empresa', 'aberta'], name='enxoval_ses_emp_abe_idx')],
            },
        ),
    ]
