# Generated by Django 4.2.30 on 2026-07-17 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0002_must_change_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('local_area', models.CharField(blank=True, max_length=120)),
                ('responsavel', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('FINALIZADO', 'Finalizado')], default='ABERTO', max_length=15)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Inventário',
                'verbose_name_plural': 'Inventários',
                'ordering': ['-data', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('ativo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'ordering': ['nome'],
                'unique_together': {('empresa', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='CategoriaBem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('taxa_depreciacao_anual', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Categoria de Bem',
                'verbose_name_plural': 'Categorias de Bens',
                'ordering': ['nome'],
                'unique_together': {('empresa', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='Bem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plaqueta', models.CharField(db_index=True, max_length=40, unique=True)),
                ('descricao', models.CharField(max_length=200)),
                ('localizacao', models.CharField(blank=True, max_length=120)),
                ('responsavel', models.CharField(blank=True, max_length=120)),
                ('nota_fiscal', models.CharField(blank=True, max_length=40)),
                ('fornecedor', models.CharField(blank=True, max_length=160)),
                ('data_aquisicao', models.DateField(blank=True, null=True)),
                ('valor_aquisicao', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('situacao', models.CharField(choices=[('EM_USO', 'Em Uso'), ('MANUTENCAO', 'Em Manutenção'), ('BAIXADO', 'Baixado')], default='EM_USO', max_length=20)),
                ('data_baixa', models.DateField(blank=True, null=True)),
                ('motivo_baixa', models.CharField(blank=True, choices=[('VENDA', 'Venda'), ('PERDA', 'Perda'), ('ROUBO', 'Roubo'), ('SUCATA', 'Sucateamento'), ('DOACAO', 'Doação'), ('OUTRO', 'Outro')], max_length=10)),
                ('observacoes', models.TextField(blank=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='imobilizado/fotos/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bens', to='imobilizado.categoriabem')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bens', to='imobilizado.departamento')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Bem',
                'verbose_name_plural': 'Bens',
                'ordering': ['plaqueta'],
            },
        ),
        migrations.CreateModel(
            name='ItemInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plaqueta_lida', models.CharField(max_length=40)),
                ('situacao', models.CharField(choices=[('LOCALIZADO', 'Localizado'), ('LOCAL_DIVERGENTE', 'Local Divergente'), ('NAO_CADASTRADO', 'Não Cadastrado')], max_length=20)),
                ('localizacao_encontrada', models.CharField(blank=True, max_length=120)),
                ('contado_por', models.CharField(blank=True, max_length=120)),
                ('contado_em', models.DateTimeField(auto_now=True)),
                ('observacao', models.CharField(blank=True, max_length=200)),
                ('bem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leituras', to='imobilizado.bem')),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='imobilizado.inventario')),
            ],
            options={
                'verbose_name': 'Item de Inventário',
                'verbose_name_plural': 'Itens de Inventário',
                'unique_together': {('inventario', 'plaqueta_lida')},
            },
        ),
        migrations.AddIndex(
            model_name='bem',
            index=models.Index(fields=['empresa', 'situacao'], name='imobilizado_empresa_b16309_idx'),
        ),
        migrations.AddIndex(
            model_name='bem',
            index=models.Index(fields=['empresa', 'categoria'], name='imobilizado_empresa_fdd885_idx'),
        ),
        migrations.AddIndex(
            model_name='bem',
            index=models.Index(fields=['empresa', 'departamento'], name='imobilizado_empresa_38102a_idx'),
        ),
    ]
