# Generated by Django 4.2.30 on 2026-06-23 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0002_must_change_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArquivoImportado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('total_registros', models.IntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Arquivo Importado',
                'verbose_name_plural': 'Arquivos Importados',
                'ordering': ['-data_upload'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoReceita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orcado_padrao', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('forecast_padrao', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Configuração de Receita',
                'verbose_name_plural': 'Configurações de Receita',
            },
        ),
        migrations.CreateModel(
            name='MetaMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(max_length=7)),
                ('orcado', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('forecast', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Meta Mensal',
                'verbose_name_plural': 'Metas Mensais',
                'ordering': ['mes'],
                'unique_together': {('empresa', 'mes')},
            },
        ),
        migrations.CreateModel(
            name='LancamentoDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('mes', models.CharField(max_length=7)),
                ('hosp', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('ab', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('outros', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('arquivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos', to='receitas.arquivoimportado')),
            ],
            options={
                'verbose_name': 'Lançamento Diário',
                'verbose_name_plural': 'Lançamentos Diários',
                'ordering': ['data'],
                'indexes': [models.Index(fields=['arquivo', 'data'], name='receitas_la_arquivo_2392b2_idx'), models.Index(fields=['mes'], name='receitas_la_mes_8534cb_idx')],
                'unique_together': {('arquivo', 'data')},
            },
        ),
        migrations.CreateModel(
            name='LancamentoAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(max_length=7)),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Lançamento Adicional',
                'verbose_name_plural': 'Lançamentos Adicionais',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['empresa', 'mes'], name='receitas_la_empresa_e4a9da_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='arquivoimportado',
            index=models.Index(fields=['empresa', 'ativo'], name='receitas_ar_empresa_0a27dc_idx'),
        ),
    ]
