# Generated by Django 4.2.30 on 2026-04-27 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0002_must_change_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='OcupacaoDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('tipo', models.CharField(choices=[('historico', 'Histórico'), ('previsao', 'Previsão')], default='historico', max_length=20)),
                ('ocup_n', models.IntegerField(default=0)),
                ('ocup_a', models.IntegerField(default=0)),
                ('ocup_f', models.IntegerField(default=0)),
                ('ocup_u', models.IntegerField(default=0)),
                ('ocup_d', models.IntegerField(default=0)),
                ('ocup_t', models.IntegerField(default=0)),
                ('ocup_n_chd', models.IntegerField(default=0)),
                ('ocup_n_ant', models.IntegerField(default=0)),
                ('hosp_n', models.IntegerField(default=0)),
                ('hosp_a', models.IntegerField(default=0)),
                ('hosp_f', models.IntegerField(default=0)),
                ('hosp_u', models.IntegerField(default=0)),
                ('hosp_d', models.IntegerField(default=0)),
                ('hosp_t', models.IntegerField(default=0)),
                ('hosp_check_in', models.IntegerField(default=0)),
                ('hosp_check_out', models.IntegerField(default=0)),
                ('check_in', models.IntegerField(default=0)),
                ('check_out', models.IntegerField(default=0)),
                ('day_use', models.IntegerField(default=0)),
                ('no_show', models.IntegerField(default=0)),
                ('uh_manutencao', models.IntegerField(default=0)),
                ('uh_interditada', models.IntegerField(default=0)),
                ('uh_rsv_tecnica', models.IntegerField(default=0)),
                ('uh_total', models.IntegerField(default=0)),
                ('uh_disp_venda', models.IntegerField(default=0)),
                ('taxa_ocup', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('taxa_ocup_abs', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('taxa_ocup_perc', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('diaria_n', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('diaria_n_bruta', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('hp', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ep', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cp', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('map_v', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fap', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('occ', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('occ_abs', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Ocupação Diária',
                'verbose_name_plural': 'Ocupações Diárias',
                'ordering': ['data'],
                'indexes': [models.Index(fields=['empresa', 'data'], name='ocupacao_oc_empresa_598639_idx'), models.Index(fields=['empresa', 'tipo'], name='ocupacao_oc_empresa_c3d9f8_idx')],
                'unique_together': {('empresa', 'data', 'tipo')},
            },
        ),
    ]
